apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-churn-app.fullname" . }}
  labels:
    {{- include "customer-churn-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "customer-churn-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "customer-churn-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "customer-churn-app.fullname" . }}-config
                  key: MODEL_PATH
            - name: PREPROCESSOR_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "customer-churn-app.fullname" . }}-config
                  key: PREPROCESSOR_PATH
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "customer-churn-app.fullname" . }}-config
                  key: LOG_LEVEL
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
